#pragma once

namespace sdk {
	enum e_weapon_type : short {
		weapon_deagle = 1,
		weapon_dualberetta = 2,
		weapon_fiveseven = 3,
		weapon_glock = 4,
		weapon_ak47 = 7,
		weapon_aug = 8,
		weapon_awp = 9,
		weapon_famas = 10,
		weapon_g3sg1 = 11,
		weapon_galil = 13,
		weapon_m249 = 14,
		weapon_m4a1 = 16,
		weapon_mac10 = 17,
		weapon_p90 = 19,
		weapon_mp5sd = 23,
		weapon_ump45 = 24,
		weapon_xm1014 = 25,
		weapon_bizon = 26,
		weapon_mag7 = 27,
		weapon_negev = 28,
		weapon_sawedoff = 29,
		weapon_tec9 = 30,
		weapon_zeusx27 = 31,
		weapon_usp = 32,
		weapon_mp7 = 33,
		weapon_mp9 = 34,
		weapon_nova = 35,
		weapon_p250 = 36,
		weapon_shield = 37,
		weapon_scar20 = 38,
		weapon_sg553 = 39,
		weapon_ssg08 = 40,
		weapon_knife_gg = 41,
		weapon_knife = 42,
		weapon_flashbang = 43,
		weapon_hegrenade = 44,
		weapon_smokegrenade = 45,
		weapon_molotov = 46,
		weapon_decoy = 47,
		weapon_inc = 48,
		weapon_c4 = 49,
		weapon_healthshot = 57,
		weapon_knife_t = 59,
		weapon_m4a1s = 60,
		weapon_usps = 61,
		weapon_cz75 = 63,
		weapon_revolver = 64,
		weapon_tagrenade = 68,
		weapon_fists = 69,
		weapon_breachcharge = 70,
		weapon_diversion = 82,
		weapon_tablet = 72,
		weapon_frag_grenade = 83,
		weapon_melee = 74,
		weapon_snowball = 84,
		weapon_axe = 75,
		weapon_bumpmine = 85,
		weapon_hammer = 76,
		weapon_firebomb = 81,
		weapon_knife_bayonet = 500,
		weapon_spanner = 78,
		weapon_knife_css = 503,
		weapon_knife_ghost = 80,
		weapon_knife_flip = 505,
		weapon_knife_gut = 506,
		weapon_knife_karambit = 507,
		weapon_knife_m9_bayonet = 508,
		weapon_knife_tactical = 509,
		weapon_knife_falchion = 512,
		weapon_knife_survival_bowie = 514,
		weapon_knife_butterfly = 515,
		weapon_knife_push = 516,
		weapon_knife_cord = 517,
		weapon_knife_canis = 518,
		weapon_knife_ursus = 519,
		weapon_knife_gypsy_jackknife = 520,
		weapon_knife_outdoor = 521,
		weapon_knife_stiletto = 522,
		weapon_knife_widowmaker = 523,
		weapon_knife_skeleton = 525,
		glove_studded_brokenfang = 4725,
		glove_studded_bloodhound = 5027,
		glove_t = 5028,
		glove_ct = 5029,
		glove_sporty = 5030,
		glove_slick = 5031,
		glove_leather_handwraps = 5032,
		glove_motorcycle = 5033,
		glove_specialist = 5034,
		glove_studded_hydra = 5035,
		special_agent_blueberries_buckshot = 4619,
		special_agent_two_times_mccoy_tacp = 4680,
		special_agent_commandor_mae_jamison = 4711,
		special_agent_1st_lieutenant_farlow,
		special_agent_john_kask,
		special_agent_bio_haz_specialist,
		special_agent_sergeant_bombson,
		special_agent_chem_haz_specialist,
		special_agent_rezan_the_redshirt = 4718,
		special_agent_sir_bloody_miami_darryl = 4726,
		special_agent_safecracker_voltzmann,
		special_agent_little_kev,
		special_agent_getaway_sally = 4730,
		special_agent_number_k = 4732,
		special_agent_sir_bloody_silent_darryl = 4733,
		special_agent_sir_bloody_skullhead_darryl,
		special_agent_sir_bloody_darryl_royale,
		special_agent_sir_bloody_loudmouth_darryl,
		special_agent_t = 5036,
		special_agent_ct = 5037,
		special_agent_ground_rebel = 5105,
		special_agent_osiris,
		special_agent_shahmat,
		special_agent_muhlik,
		special_agent_soldier = 5205,
		special_agent_enforcer,
		special_agent_slingshot,
		special_agent_street_soldier,
		special_agent_operator = 5305,
		special_agent_markus_delrow,
		special_agent_michael_syfers,
		special_agent_ava,
		special_agent_3rd_commando_company = 5400,
		special_agent_seal_team_6_soldier,
		special_agent_buckshot,
		special_agent_two_times_mccoy_usaf,
		special_agent_ricksaw,
		special_agent_dragomir = 5500,
		special_agent_maximus,
		special_agent_rezan_the_ready,
		special_agent_blackwolf = 5503,
		special_agent_the_doctor,
		special_agent_dragomir_footsoldiers,
		special_agent_b_squadron_officer = 5601,
		__max
	};

	inline std::unordered_map<e_weapon_type, std::string> weapon_names = []() -> std::unordered_map<e_weapon_type, std::string> {
		return {
			{ e_weapon_type::weapon_knife, STRS("Knife") },
			{ e_weapon_type::glove_t, STRS("Gloves") },
			{ e_weapon_type::weapon_ak47, STRS("AK-47") },
			{ e_weapon_type::weapon_aug, STRS("AUG") },
			{ e_weapon_type::weapon_awp, STRS("AWP") },
			{ e_weapon_type::weapon_cz75, STRS("CZ75 Auto") },
			{ e_weapon_type::weapon_deagle, STRS("Desert Eagle") },
			{ e_weapon_type::weapon_dualberetta, STRS("Dual Berettas") },
			{ e_weapon_type::weapon_famas, STRS("FAMAS") },
			{ e_weapon_type::weapon_fiveseven, STRS("Five-SeveN") },
			{ e_weapon_type::weapon_g3sg1, STRS("G3SG1") },
			{ e_weapon_type::weapon_galil, STRS("Galil AR") },
			{ e_weapon_type::weapon_glock, STRS("Glock-18") },
			{ e_weapon_type::weapon_m249, STRS("M249") },
			{ e_weapon_type::weapon_m4a1s, STRS("M4A1-S") },
			{ e_weapon_type::weapon_m4a1, STRS("M4A4") },
			{ e_weapon_type::weapon_mac10, STRS("MAC-10") },
			{ e_weapon_type::weapon_mag7, STRS("MAG-7") },
			{ e_weapon_type::weapon_mp7, STRS("MP7") },
			{ e_weapon_type::weapon_mp9, STRS("MP9") },
			{ e_weapon_type::weapon_negev, STRS("Negev") },
			{ e_weapon_type::weapon_nova, STRS("Nova") },
			{ e_weapon_type::weapon_usp, STRS("P2000") },
			{ e_weapon_type::weapon_p250, STRS("P250") },
			{ e_weapon_type::weapon_p90, STRS("P90") },
			{ e_weapon_type::weapon_bizon, STRS("PP-Bizon") },
			{ e_weapon_type::weapon_revolver, STRS("R8 Revolver") },
			{ e_weapon_type::weapon_sawedoff, STRS("Sawed-Off") },
			{ e_weapon_type::weapon_scar20, STRS("SCAR-20") },
			{ e_weapon_type::weapon_ssg08, STRS("SSG 08") },
			{ e_weapon_type::weapon_sg553, STRS("SG 553") },
			{ e_weapon_type::weapon_tec9, STRS("Tec-9") },
			{ e_weapon_type::weapon_ump45, STRS("UMP-45") },
			{ e_weapon_type::weapon_usps, STRS("USP-S") },
			{ e_weapon_type::weapon_xm1014, STRS("XM1014") },
		};
	}();
} // namespace sdk